export const AFGHANISTAN_FLAG_EMOJI = '🇦🇫';
export const ALAND_ISLANDS_FLAG_EMOJI = '🇦🇽';
export const ALBANIA_FLAG_EMOJI = '🇦🇱';
export const ALGERIA_FLAG_EMOJI = '🇩🇿';
export const AMERICAN_SAMOA_FLAG_EMOJI = '🇦🇸';
export const ANDORRA_FLAG_EMOJI = '🇦🇩';
export const ANGOLA_FLAG_EMOJI = '🇦🇴';
export const ANGUILLA_FLAG_EMOJI = '🇦🇮';
export const ANTARCTICA_FLAG_EMOJI = '🇦🇶';
export const ANTIGUA_AND_BARBUDA_FLAG_EMOJI = '🇦🇬';
export const ARGENTINA_FLAG_EMOJI = '🇦🇷';
export const ARMENIA_FLAG_EMOJI = '🇦🇲';
export const ARUBA_FLAG_EMOJI = '🇦🇼';
export const ASCENSION_ISLAND_FLAG_EMOJI = '🇦🇨';
export const AUSTRALIA_FLAG_EMOJI = '🇦🇺';
export const AUSTRIA_FLAG_EMOJI = '🇦🇹';
export const AZERBAIJAN_FLAG_EMOJI = '🇦🇿';
export const BAHAMAS_FLAG_EMOJI = '🇧🇸';
export const BAHRAIN_FLAG_EMOJI = '🇧🇭';
export const BANGLADESH_FLAG_EMOJI = '🇧🇩';
export const BARBADOS_FLAG_EMOJI = '🇧🇧';
export const BELARUS_FLAG_EMOJI = '🇧🇾';
export const BELGIUM_FLAG_EMOJI = '🇧🇪';
export const BELIZE_FLAG_EMOJI = '🇧🇿';
export const BENIN_FLAG_EMOJI = '🇧🇯';
export const BERMUDA_FLAG_EMOJI = '🇧🇲';
export const BHUTAN_FLAG_EMOJI = '🇧🇹';
export const BOLIVIA_FLAG_EMOJI = '🇧🇴';
export const BONAIRE_FLAG_EMOJI = '🇧🇶';
export const BOSNIA_AND_HERZEGOVINA_FLAG_EMOJI = '🇧🇦';
export const BOTSWANA_FLAG_EMOJI = '🇧🇼';
export const BOUVET_ISLAND_FLAG_EMOJI = '🇧🇻';
export const BRAZIL_FLAG_EMOJI = '🇧🇷';
export const BRITISH_INDIAN_OCEAN_TERRITORY_FLAG_EMOJI = '🇮🇴';
export const BRITISH_VIRGIN_ISLANDS_FLAG_EMOJI = '🇻🇬';
export const BRUNEI_FLAG_EMOJI = '🇧🇳';
export const BULGARIA_FLAG_EMOJI = '🇧🇬';
export const BURKINA_FASO_FLAG_EMOJI = '🇧🇫';
export const BURUNDI_FLAG_EMOJI = '🇧🇮';
export const CAMBODIA_FLAG_EMOJI = '🇰🇭';
export const CAMEROON_FLAG_EMOJI = '🇨🇲';
export const CANADA_FLAG_EMOJI = '🇨🇦';
export const CANARY_ISLANDS_FLAG_EMOJI = '🇮🇨';
export const CAPE_VERDE_FLAG_EMOJI = '🇨🇻';
export const CARIBBEAN_NETHERLANDS_FLAG_EMOJI = '🇧🇶';
export const CAYMAN_ISLANDS_FLAG_EMOJI = '🇰🇾';
export const CENTRAL_AFRICAN_REPUBLIC_FLAG_EMOJI = '🇨🇫';
export const CEUTA_AND_MELILLA_FLAG_EMOJI = '🇪🇦';
export const CHAD_FLAG_EMOJI = '🇹🇩';
export const CHILE_FLAG_EMOJI = '🇨🇱';
export const CHINA_FLAG_EMOJI = '🇨🇳';
export const CHRISTMAS_ISLAND_FLAG_EMOJI = '🇨🇽';
export const CLIPPERTON_ISLAND_FLAG_EMOJI = '🇨🇵';
export const COCOS_KEELING_ISLANDS_FLAG_EMOJI = '🇨🇨';
export const COLOMBIA_FLAG_EMOJI = '🇨🇴';
export const COMOROS_FLAG_EMOJI = '🇰🇲';
export const CONGO_BRAZZAVILLE_FLAG_EMOJI = '🇨🇬';
export const CONGO_KINSHASA_FLAG_EMOJI = '🇨🇩';
export const COOK_ISLANDS_FLAG_EMOJI = '🇨🇰';
export const COSTA_RICA_FLAG_EMOJI = '🇨🇷';
export const CROATIA_FLAG_EMOJI = '🇭🇷';
export const CUBA_FLAG_EMOJI = '🇨🇺';
export const CURACAO_FLAG_EMOJI = '🇨🇼';
export const CYPRUS_FLAG_EMOJI = '🇨🇾';
export const CZECHIA_FLAG_EMOJI = '🇨🇿';
export const DENMARK_FLAG_EMOJI = '🇩🇰';
export const DIEGO_GARCIA_FLAG_EMOJI = '🇩🇬';
export const DJIBOUTI_FLAG_EMOJI = '🇩🇯';
export const DOMINICA_FLAG_EMOJI = '🇩🇲';
export const DOMINICAN_REPUBLIC_FLAG_EMOJI = '🇩🇴';
export const ECUADOR_FLAG_EMOJI = '🇪🇨';
export const EGYPT_FLAG_EMOJI = '🇪🇬';
export const EL_SALVADOR_FLAG_EMOJI = '🇸🇻';
export const ENGLAND_FLAG_EMOJI = '🏴󠁧󠁢󠁥󠁮󠁧󠁿';
export const EQUATORIAL_GUINEA_FLAG_EMOJI = '🇬🇶';
export const ERITREA_FLAG_EMOJI = '🇪🇷';
export const ESTONIA_FLAG_EMOJI = '🇪🇪';
export const ESWATINI_FLAG_EMOJI = '🇸🇿';
export const ETHIOPIA_FLAG_EMOJI = '🇪🇹';
export const FALKLAND_ISLANDS_FLAG_EMOJI = '🇫🇰';
export const FAROE_ISLANDS_FLAG_EMOJI = '🇫🇴';
export const FIJI_FLAG_EMOJI = '🇫🇯';
export const FINLAND_FLAG_EMOJI = '🇫🇮';
export const FRANCE_FLAG_EMOJI = '🇫🇷';
export const FRENCH_GUIANA_FLAG_EMOJI = '🇬🇫';
export const FRENCH_POLYNESIA_FLAG_EMOJI = '🇵🇫';
export const FRENCH_SOUTHERN_TERRITORIES_FLAG_EMOJI = '🇹🇫';
export const GABON_FLAG_EMOJI = '🇬🇦';
export const GAMBIA_FLAG_EMOJI = '🇬🇲';
export const GEORGIA_FLAG_EMOJI = '🇬🇪';
export const GERMANY_FLAG_EMOJI = '🇩🇪';
export const GHANA_FLAG_EMOJI = '🇬🇭';
export const GIBRALTAR_FLAG_EMOJI = '🇬🇮';
export const GREECE_FLAG_EMOJI = '🇬🇷';
export const GREENLAND_FLAG_EMOJI = '🇬🇱';
export const GRENADA_FLAG_EMOJI = '🇬🇩';
export const GUADELOUPE_FLAG_EMOJI = '🇬🇵';
export const GUAM_FLAG_EMOJI = '🇬🇺';
export const GUATEMALA_FLAG_EMOJI = '🇬🇹';
export const GUERNSEY_FLAG_EMOJI = '🇬🇬';
export const GUINEA_FLAG_EMOJI = '🇬🇳';
export const GUINEA_BISSAU_FLAG_EMOJI = '🇬🇼';
export const GUYANA_FLAG_EMOJI = '🇬🇾';
export const HAITI_FLAG_EMOJI = '🇭🇹';
export const HEARD_AND_MCDONALD_ISLANDS_FLAG_EMOJI = '🇭🇲';
export const HONDURAS_FLAG_EMOJI = '🇭🇳';
export const HONG_KONG_FLAG_EMOJI = '🇭🇰';
export const HUNGARY_FLAG_EMOJI = '🇭🇺';
export const ICELAND_FLAG_EMOJI = '🇮🇸';
export const INDIA_FLAG_EMOJI = '🇮🇳';
export const INDONESIA_FLAG_EMOJI = '🇮🇩';
export const IRAN_FLAG_EMOJI = '🇮🇷';
export const IRAQ_FLAG_EMOJI = '🇮🇶';
export const IRELAND_FLAG_EMOJI = '🇮🇪';
export const ISLE_OF_MAN_FLAG_EMOJI = '🇮🇲';
export const ISRAEL_FLAG_EMOJI = '🇮🇱';
export const ITALY_FLAG_EMOJI = '🇮🇹';
export const IVORY_COAST_FLAG_EMOJI = '🇨🇮';
export const JAMAICA_FLAG_EMOJI = '🇯🇲';
export const JAPAN_FLAG_EMOJI = '🇯🇵';
export const JERSEY_FLAG_EMOJI = '🇯🇪';
export const JORDAN_FLAG_EMOJI = '🇯🇴';
export const KAZAKHSTAN_FLAG_EMOJI = '🇰🇿';
export const KENYA_FLAG_EMOJI = '🇰🇪';
export const KIRIBATI_FLAG_EMOJI = '🇰🇮';
export const KOSOVO_FLAG_EMOJI = '🇽🇰';
export const KUWAIT_FLAG_EMOJI = '🇰🇼';
export const KYRGYZSTAN_FLAG_EMOJI = '🇰🇬';
export const LAOS_FLAG_EMOJI = '🇱🇦';
export const LATVIA_FLAG_EMOJI = '🇱🇻';
export const LEBANON_FLAG_EMOJI = '🇱🇧';
export const LESOTHO_FLAG_EMOJI = '🇱🇸';
export const LIBERIA_FLAG_EMOJI = '🇱🇷';
export const LIBYA_FLAG_EMOJI = '🇱🇾';
export const LIECHTENSTEIN_FLAG_EMOJI = '🇱🇮';
export const LITHUANIA_FLAG_EMOJI = '🇱🇹';
export const LUXEMBOURG_FLAG_EMOJI = '🇱🇺';
export const MACAO_FLAG_EMOJI = '🇲🇴';
export const MADAGASCAR_FLAG_EMOJI = '🇲🇬';
export const MALAWI_FLAG_EMOJI = '🇲🇼';
export const MALAYSIA_FLAG_EMOJI = '🇲🇾';
export const MALDIVES_FLAG_EMOJI = '🇲🇻';
export const MALI_FLAG_EMOJI = '🇲🇱';
export const MALTA_FLAG_EMOJI = '🇲🇹';
export const MARSHALL_ISLANDS_FLAG_EMOJI = '🇲🇭';
export const MARTINIQUE_FLAG_EMOJI = '🇲🇶';
export const MAURITANIA_FLAG_EMOJI = '🇲🇷';
export const MAURITIUS_FLAG_EMOJI = '🇲🇺';
export const MAYOTTE_FLAG_EMOJI = '🇾🇹';
export const MEXICO_FLAG_EMOJI = '🇲🇽';
export const MICRONESIA_FLAG_EMOJI = '🇫🇲';
export const MOLDOVA_FLAG_EMOJI = '🇲🇩';
export const MONACO_FLAG_EMOJI = '🇲🇨';
export const MONGOLIA_FLAG_EMOJI = '🇲🇳';
export const MONTENEGRO_FLAG_EMOJI = '🇲🇪';
export const MONTSERRAT_FLAG_EMOJI = '🇲🇸';
export const MOROCCO_FLAG_EMOJI = '🇲🇦';
export const MOZAMBIQUE_FLAG_EMOJI = '🇲🇿';
export const MYANMAR_FLAG_EMOJI = '🇲🇲';
export const NAMIBIA_FLAG_EMOJI = '🇳🇦';
export const NAURU_FLAG_EMOJI = '🇳🇷';
export const NEPAL_FLAG_EMOJI = '🇳🇵';
export const NETHERLANDS_FLAG_EMOJI = '🇳🇱';
export const NEW_CALEDONIA_FLAG_EMOJI = '🇳🇨';
export const NEW_ZEALAND_FLAG_EMOJI = '🇳🇿';
export const NICARAGUA_FLAG_EMOJI = '🇳🇮';
export const NIGER_FLAG_EMOJI = '🇳🇪';
export const NIGERIA_FLAG_EMOJI = '🇳🇬';
export const NIUE_FLAG_EMOJI = '🇳🇺';
export const NORFOLK_ISLAND_FLAG_EMOJI = '🇳🇫';
export const NORTH_KOREA_FLAG_EMOJI = '🇰🇵';
export const NORTH_MACEDONIA_FLAG_EMOJI = '🇲🇰';
export const NORTHERN_MARIANA_ISLANDS_FLAG_EMOJI = '🇲🇵';
export const NORWAY_FLAG_EMOJI = '🇳🇴';
export const OMAN_FLAG_EMOJI = '🇴🇲';
export const PAKISTAN_FLAG_EMOJI = '🇵🇰';
export const PALAU_FLAG_EMOJI = '🇵🇼';
export const PALESTINE_FLAG_EMOJI = '🇵🇸';
export const PANAMA_FLAG_EMOJI = '🇵🇦';
export const PAPUA_NEW_GUINEA_FLAG_EMOJI = '🇵🇬';
export const PARAGUAY_FLAG_EMOJI = '🇵🇾';
export const PERU_FLAG_EMOJI = '🇵🇪';
export const PHILIPPINES_FLAG_EMOJI = '🇵🇭';
export const PITCAIRN_ISLANDS_FLAG_EMOJI = '🇵🇳';
export const POLAND_FLAG_EMOJI = '🇵🇱';
export const PORTUGAL_FLAG_EMOJI = '🇵🇹';
export const PUERTO_RICO_FLAG_EMOJI = '🇵🇷';
export const QATAR_FLAG_EMOJI = '🇶🇦';
export const REUNION_FLAG_EMOJI = '🇷🇪';
export const ROMANIA_FLAG_EMOJI = '🇷🇴';
export const RUSSIA_FLAG_EMOJI = '🇷🇺';
export const RWANDA_FLAG_EMOJI = '🇷🇼';
export const SAMOA_FLAG_EMOJI = '🇼🇸';
export const SAN_MARINO_FLAG_EMOJI = '🇸🇲';
export const SAO_TOME_AND_PRINCIPE_FLAG_EMOJI = '🇸🇹';
export const SAUDI_ARABIA_FLAG_EMOJI = '🇸🇦';
export const SCOTLAND_FLAG_EMOJI = '🏴󠁧󠁢󠁳󠁣󠁴󠁿';
export const SENEGAL_FLAG_EMOJI = '🇸🇳';
export const SERBIA_FLAG_EMOJI = '🇷🇸';
export const SEYCHELLES_FLAG_EMOJI = '🇸🇨';
export const SIERRA_LEONE_FLAG_EMOJI = '🇸🇱';
export const SINGAPORE_FLAG_EMOJI = '🇸🇬';
export const SINT_MAARTEN_FLAG_EMOJI = '🇸🇽';
export const SLOVAKIA_FLAG_EMOJI = '🇸🇰';
export const SLOVENIA_FLAG_EMOJI = '🇸🇮';
export const SOLOMON_ISLANDS_FLAG_EMOJI = '🇸🇧';
export const SOMALIA_FLAG_EMOJI = '🇸🇴';
export const SOUTH_AFRICA_FLAG_EMOJI = '🇿🇦';
export const SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS_FLAG_EMOJI = '🇬🇸';
export const SOUTH_KOREA_FLAG_EMOJI = '🇰🇷';
export const SOUTH_SUDAN_FLAG_EMOJI = '🇸🇸';
export const SPAIN_FLAG_EMOJI = '🇪🇸';
export const SRI_LANKA_FLAG_EMOJI = '🇱🇰';
export const ST_BARTHELEMY_FLAG_EMOJI = '🇧🇱';
export const ST_HELENA_FLAG_EMOJI = '🇸🇭';
export const ST_KITTS_AND_NEVIS_FLAG_EMOJI = '🇰🇳';
export const ST_LUCIA_FLAG_EMOJI = '🇱🇨';
export const ST_MARTIN_FLAG_EMOJI = '🇲🇫';
export const ST_PIERRE_AND_MIQUELON_FLAG_EMOJI = '🇵🇲';
export const ST_VINCENT_AND_GRENADINES_FLAG_EMOJI = '🇻🇨';
export const SUDAN_FLAG_EMOJI = '🇸🇩';
export const SURINAME_FLAG_EMOJI = '🇸🇷';
export const SVALBARD_AND_JAN_MAYEN_FLAG_EMOJI = '🇸🇯';
export const SWEDEN_FLAG_EMOJI = '🇸🇪';
export const SWITZERLAND_FLAG_EMOJI = '🇨🇭';
export const SYRIA_FLAG_EMOJI = '🇸🇾';
export const TAIWAN_FLAG_EMOJI = '🇹🇼';
export const TAJIKISTAN_FLAG_EMOJI = '🇹🇯';
export const TANZANIA_FLAG_EMOJI = '🇹🇿';
export const THAILAND_FLAG_EMOJI = '🇹🇭';
export const TIMOR_LESTE_FLAG_EMOJI = '🇹🇱';
export const TOGO_FLAG_EMOJI = '🇹🇬';
export const TOKELAU_FLAG_EMOJI = '🇹🇰';
export const TONGA_FLAG_EMOJI = '🇹🇴';
export const TRINIDAD_AND_TOBAGO_FLAG_EMOJI = '🇹🇹';
export const TRISTAN_DA_CUNHA_FLAG_EMOJI = '🇹🇦';
export const TUNISIA_FLAG_EMOJI = '🇹🇳';
export const TURKEY_FLAG_EMOJI = '🇹🇷';
export const TURKMENISTAN_FLAG_EMOJI = '🇹🇲';
export const TURKS_AND_CAICOS_ISLANDS_FLAG_EMOJI = '🇹🇨';
export const TUVALU_FLAG_EMOJI = '🇹🇻';
export const US_VIRGIN_ISLANDS_FLAG_EMOJI = '🇻🇮';
export const UGANDA_FLAG_EMOJI = '🇺🇬';
export const UKRAINE_FLAG_EMOJI = '🇺🇦';
export const UNITED_ARAB_EMIRATES_FLAG_EMOJI = '🇦🇪';
export const UNITED_STATES_FLAG_EMOJI = '🇺🇸';
export const URUGUAY_FLAG_EMOJI = '🇺🇾';
export const UZBEKISTAN_FLAG_EMOJI = '🇺🇿';
export const VANUATU_FLAG_EMOJI = '🇻🇺';
export const VATICAN_CITY_FLAG_EMOJI = '🇻🇦';
export const VENEZUELA_FLAG_EMOJI = '🇻🇪';
export const VIETNAM_FLAG_EMOJI = '🇻🇳';
export const WALES_FLAG_EMOJI = '🏴󠁧󠁢󠁷󠁬󠁳󠁿';
export const WALLIS_AND_FUTUNA_FLAG_EMOJI = '🇼🇫';
export const WESTERN_SAHARA_FLAG_EMOJI = '🇪🇭';
export const YEMEN_FLAG_EMOJI = '🇾🇪';
export const ZAMBIA_FLAG_EMOJI = '🇿🇲';
export const ZIMBABWE_FLAG_EMOJI = '🇿🇼';

export const UNITED_KINGDOM_FLAG_EMOJI = '🇬🇧';
export const UNITED_NATIONS_FLAG_EMOJI = '🇺🇳';
export const EUROPEAN_UNION_FLAG_EMOJI = '🇪🇺';

export const RAINBOW_FLAG_EMOJI = '🏳️‍🌈';
export const TRANS_FLAG_EMOJI = '🏳️‍⚧️';

export const CHEQUERED_FLAG_EMOJI = '🏁';
export const PIRATE_FLAG_EMOJI = '🏴‍☠️';
export const BLACK_FLAG_EMOJI = '🏴';
export const WHITE_FLAG_EMOJI = '🏳';
export const TRIANGULAR_FLAG_EMOJI = '🚩';
export const CROSSED_FLAGS_EMOJI = '🎌';

export const COUNTRY_FLAGS = [
  AFGHANISTAN_FLAG_EMOJI,
  ALAND_ISLANDS_FLAG_EMOJI,
  ALBANIA_FLAG_EMOJI,
  ALGERIA_FLAG_EMOJI,
  AMERICAN_SAMOA_FLAG_EMOJI,
  ANDORRA_FLAG_EMOJI,
  ANGOLA_FLAG_EMOJI,
  ANGUILLA_FLAG_EMOJI,
  ANTARCTICA_FLAG_EMOJI,
  ANTIGUA_AND_BARBUDA_FLAG_EMOJI,
  ARGENTINA_FLAG_EMOJI,
  ARMENIA_FLAG_EMOJI,
  ARUBA_FLAG_EMOJI,
  ASCENSION_ISLAND_FLAG_EMOJI,
  AUSTRALIA_FLAG_EMOJI,
  AUSTRIA_FLAG_EMOJI,
  AZERBAIJAN_FLAG_EMOJI,
  BAHAMAS_FLAG_EMOJI,
  BAHRAIN_FLAG_EMOJI,
  BANGLADESH_FLAG_EMOJI,
  BARBADOS_FLAG_EMOJI,
  BELARUS_FLAG_EMOJI,
  BELGIUM_FLAG_EMOJI,
  BELIZE_FLAG_EMOJI,
  BENIN_FLAG_EMOJI,
  BERMUDA_FLAG_EMOJI,
  BHUTAN_FLAG_EMOJI,
  BOLIVIA_FLAG_EMOJI,
  BONAIRE_FLAG_EMOJI,
  BOSNIA_AND_HERZEGOVINA_FLAG_EMOJI,
  BOTSWANA_FLAG_EMOJI,
  BOUVET_ISLAND_FLAG_EMOJI,
  BRAZIL_FLAG_EMOJI,
  BRITISH_INDIAN_OCEAN_TERRITORY_FLAG_EMOJI,
  BRITISH_VIRGIN_ISLANDS_FLAG_EMOJI,
  BRUNEI_FLAG_EMOJI,
  BULGARIA_FLAG_EMOJI,
  BURKINA_FASO_FLAG_EMOJI,
  BURUNDI_FLAG_EMOJI,
  CAMBODIA_FLAG_EMOJI,
  CAMEROON_FLAG_EMOJI,
  CANADA_FLAG_EMOJI,
  CANARY_ISLANDS_FLAG_EMOJI,
  CAPE_VERDE_FLAG_EMOJI,
  CARIBBEAN_NETHERLANDS_FLAG_EMOJI,
  CAYMAN_ISLANDS_FLAG_EMOJI,
  CENTRAL_AFRICAN_REPUBLIC_FLAG_EMOJI,
  CEUTA_AND_MELILLA_FLAG_EMOJI,
  CHAD_FLAG_EMOJI,
  CHILE_FLAG_EMOJI,
  CHINA_FLAG_EMOJI,
  CHRISTMAS_ISLAND_FLAG_EMOJI,
  CLIPPERTON_ISLAND_FLAG_EMOJI,
  COCOS_KEELING_ISLANDS_FLAG_EMOJI,
  COLOMBIA_FLAG_EMOJI,
  COMOROS_FLAG_EMOJI,
  CONGO_BRAZZAVILLE_FLAG_EMOJI,
  CONGO_KINSHASA_FLAG_EMOJI,
  COOK_ISLANDS_FLAG_EMOJI,
  COSTA_RICA_FLAG_EMOJI,
  CROATIA_FLAG_EMOJI,
  CUBA_FLAG_EMOJI,
  CURACAO_FLAG_EMOJI,
  CYPRUS_FLAG_EMOJI,
  CZECHIA_FLAG_EMOJI,
  DENMARK_FLAG_EMOJI,
  DIEGO_GARCIA_FLAG_EMOJI,
  DJIBOUTI_FLAG_EMOJI,
  DOMINICA_FLAG_EMOJI,
  DOMINICAN_REPUBLIC_FLAG_EMOJI,
  ECUADOR_FLAG_EMOJI,
  EGYPT_FLAG_EMOJI,
  EL_SALVADOR_FLAG_EMOJI,
  ENGLAND_FLAG_EMOJI,
  EQUATORIAL_GUINEA_FLAG_EMOJI,
  ERITREA_FLAG_EMOJI,
  ESTONIA_FLAG_EMOJI,
  ESWATINI_FLAG_EMOJI,
  ETHIOPIA_FLAG_EMOJI,
  FALKLAND_ISLANDS_FLAG_EMOJI,
  FAROE_ISLANDS_FLAG_EMOJI,
  FIJI_FLAG_EMOJI,
  FINLAND_FLAG_EMOJI,
  FRANCE_FLAG_EMOJI,
  FRENCH_GUIANA_FLAG_EMOJI,
  FRENCH_POLYNESIA_FLAG_EMOJI,
  FRENCH_SOUTHERN_TERRITORIES_FLAG_EMOJI,
  GABON_FLAG_EMOJI,
  GAMBIA_FLAG_EMOJI,
  GEORGIA_FLAG_EMOJI,
  GERMANY_FLAG_EMOJI,
  GHANA_FLAG_EMOJI,
  GIBRALTAR_FLAG_EMOJI,
  GREECE_FLAG_EMOJI,
  GREENLAND_FLAG_EMOJI,
  GRENADA_FLAG_EMOJI,
  GUADELOUPE_FLAG_EMOJI,
  GUAM_FLAG_EMOJI,
  GUATEMALA_FLAG_EMOJI,
  GUERNSEY_FLAG_EMOJI,
  GUINEA_FLAG_EMOJI,
  GUINEA_BISSAU_FLAG_EMOJI,
  GUYANA_FLAG_EMOJI,
  HAITI_FLAG_EMOJI,
  HEARD_AND_MCDONALD_ISLANDS_FLAG_EMOJI,
  HONDURAS_FLAG_EMOJI,
  HONG_KONG_FLAG_EMOJI,
  HUNGARY_FLAG_EMOJI,
  ICELAND_FLAG_EMOJI,
  INDIA_FLAG_EMOJI,
  INDONESIA_FLAG_EMOJI,
  IRAN_FLAG_EMOJI,
  IRAQ_FLAG_EMOJI,
  IRELAND_FLAG_EMOJI,
  ISLE_OF_MAN_FLAG_EMOJI,
  ISRAEL_FLAG_EMOJI,
  ITALY_FLAG_EMOJI,
  IVORY_COAST_FLAG_EMOJI,
  JAMAICA_FLAG_EMOJI,
  JAPAN_FLAG_EMOJI,
  JERSEY_FLAG_EMOJI,
  JORDAN_FLAG_EMOJI,
  KAZAKHSTAN_FLAG_EMOJI,
  KENYA_FLAG_EMOJI,
  KIRIBATI_FLAG_EMOJI,
  KOSOVO_FLAG_EMOJI,
  KUWAIT_FLAG_EMOJI,
  KYRGYZSTAN_FLAG_EMOJI,
  LAOS_FLAG_EMOJI,
  LATVIA_FLAG_EMOJI,
  LEBANON_FLAG_EMOJI,
  LESOTHO_FLAG_EMOJI,
  LIBERIA_FLAG_EMOJI,
  LIBYA_FLAG_EMOJI,
  LIECHTENSTEIN_FLAG_EMOJI,
  LITHUANIA_FLAG_EMOJI,
  LUXEMBOURG_FLAG_EMOJI,
  MACAO_FLAG_EMOJI,
  MADAGASCAR_FLAG_EMOJI,
  MALAWI_FLAG_EMOJI,
  MALAYSIA_FLAG_EMOJI,
  MALDIVES_FLAG_EMOJI,
  MALI_FLAG_EMOJI,
  MALTA_FLAG_EMOJI,
  MARSHALL_ISLANDS_FLAG_EMOJI,
  MARTINIQUE_FLAG_EMOJI,
  MAURITANIA_FLAG_EMOJI,
  MAURITIUS_FLAG_EMOJI,
  MAYOTTE_FLAG_EMOJI,
  MEXICO_FLAG_EMOJI,
  MICRONESIA_FLAG_EMOJI,
  MOLDOVA_FLAG_EMOJI,
  MONACO_FLAG_EMOJI,
  MONGOLIA_FLAG_EMOJI,
  MONTENEGRO_FLAG_EMOJI,
  MONTSERRAT_FLAG_EMOJI,
  MOROCCO_FLAG_EMOJI,
  MOZAMBIQUE_FLAG_EMOJI,
  MYANMAR_FLAG_EMOJI,
  NAMIBIA_FLAG_EMOJI,
  NAURU_FLAG_EMOJI,
  NEPAL_FLAG_EMOJI,
  NETHERLANDS_FLAG_EMOJI,
  NEW_CALEDONIA_FLAG_EMOJI,
  NEW_ZEALAND_FLAG_EMOJI,
  NICARAGUA_FLAG_EMOJI,
  NIGER_FLAG_EMOJI,
  NIGERIA_FLAG_EMOJI,
  NIUE_FLAG_EMOJI,
  NORFOLK_ISLAND_FLAG_EMOJI,
  NORTH_KOREA_FLAG_EMOJI,
  NORTH_MACEDONIA_FLAG_EMOJI,
  NORTHERN_MARIANA_ISLANDS_FLAG_EMOJI,
  NORWAY_FLAG_EMOJI,
  OMAN_FLAG_EMOJI,
  PAKISTAN_FLAG_EMOJI,
  PALAU_FLAG_EMOJI,
  PALESTINE_FLAG_EMOJI,
  PANAMA_FLAG_EMOJI,
  PAPUA_NEW_GUINEA_FLAG_EMOJI,
  PARAGUAY_FLAG_EMOJI,
  PERU_FLAG_EMOJI,
  PHILIPPINES_FLAG_EMOJI,
  PITCAIRN_ISLANDS_FLAG_EMOJI,
  POLAND_FLAG_EMOJI,
  PORTUGAL_FLAG_EMOJI,
  PUERTO_RICO_FLAG_EMOJI,
  QATAR_FLAG_EMOJI,
  REUNION_FLAG_EMOJI,
  ROMANIA_FLAG_EMOJI,
  RUSSIA_FLAG_EMOJI,
  RWANDA_FLAG_EMOJI,
  SAMOA_FLAG_EMOJI,
  SAN_MARINO_FLAG_EMOJI,
  SAO_TOME_AND_PRINCIPE_FLAG_EMOJI,
  SAUDI_ARABIA_FLAG_EMOJI,
  SCOTLAND_FLAG_EMOJI,
  SENEGAL_FLAG_EMOJI,
  SERBIA_FLAG_EMOJI,
  SEYCHELLES_FLAG_EMOJI,
  SIERRA_LEONE_FLAG_EMOJI,
  SINGAPORE_FLAG_EMOJI,
  SINT_MAARTEN_FLAG_EMOJI,
  SLOVAKIA_FLAG_EMOJI,
  SLOVENIA_FLAG_EMOJI,
  SOLOMON_ISLANDS_FLAG_EMOJI,
  SOMALIA_FLAG_EMOJI,
  SOUTH_AFRICA_FLAG_EMOJI,
  SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS_FLAG_EMOJI,
  SOUTH_KOREA_FLAG_EMOJI,
  SOUTH_SUDAN_FLAG_EMOJI,
  SPAIN_FLAG_EMOJI,
  SRI_LANKA_FLAG_EMOJI,
  ST_BARTHELEMY_FLAG_EMOJI,
  ST_HELENA_FLAG_EMOJI,
  ST_KITTS_AND_NEVIS_FLAG_EMOJI,
  ST_LUCIA_FLAG_EMOJI,
  ST_MARTIN_FLAG_EMOJI,
  ST_PIERRE_AND_MIQUELON_FLAG_EMOJI,
  ST_VINCENT_AND_GRENADINES_FLAG_EMOJI,
  SUDAN_FLAG_EMOJI,
  SURINAME_FLAG_EMOJI,
  SVALBARD_AND_JAN_MAYEN_FLAG_EMOJI,
  SWEDEN_FLAG_EMOJI,
  SWITZERLAND_FLAG_EMOJI,
  SYRIA_FLAG_EMOJI,
  TAIWAN_FLAG_EMOJI,
  TAJIKISTAN_FLAG_EMOJI,
  TANZANIA_FLAG_EMOJI,
  THAILAND_FLAG_EMOJI,
  TIMOR_LESTE_FLAG_EMOJI,
  TOGO_FLAG_EMOJI,
  TOKELAU_FLAG_EMOJI,
  TONGA_FLAG_EMOJI,
  TRINIDAD_AND_TOBAGO_FLAG_EMOJI,
  TRISTAN_DA_CUNHA_FLAG_EMOJI,
  TUNISIA_FLAG_EMOJI,
  TURKEY_FLAG_EMOJI,
  TURKMENISTAN_FLAG_EMOJI,
  TURKS_AND_CAICOS_ISLANDS_FLAG_EMOJI,
  TUVALU_FLAG_EMOJI,
  US_VIRGIN_ISLANDS_FLAG_EMOJI,
  UGANDA_FLAG_EMOJI,
  UKRAINE_FLAG_EMOJI,
  UNITED_ARAB_EMIRATES_FLAG_EMOJI,
  UNITED_STATES_FLAG_EMOJI,
  URUGUAY_FLAG_EMOJI,
  UZBEKISTAN_FLAG_EMOJI,
  VANUATU_FLAG_EMOJI,
  VATICAN_CITY_FLAG_EMOJI,
  VENEZUELA_FLAG_EMOJI,
  VIETNAM_FLAG_EMOJI,
  WALES_FLAG_EMOJI,
  WALLIS_AND_FUTUNA_FLAG_EMOJI,
  WESTERN_SAHARA_FLAG_EMOJI,
  YEMEN_FLAG_EMOJI,
  ZAMBIA_FLAG_EMOJI,
  ZIMBABWE_FLAG_EMOJI,
] as const;

export const COUNTRY_UNIONS_FLAGS = [
  UNITED_KINGDOM_FLAG_EMOJI,
  UNITED_NATIONS_FLAG_EMOJI,
  EUROPEAN_UNION_FLAG_EMOJI,
] as const;

// @internal
type CountryFlag = (typeof COUNTRY_FLAGS)[number];
// @internal
type UnionsFlag = (typeof COUNTRY_UNIONS_FLAGS)[number];
// @internal
type GeoFlag = CountryFlag | UnionsFlag;

export const GEO_FLAGS: readonly GeoFlag[] = [
  ...(COUNTRY_FLAGS as unknown as GeoFlag[]),
  ...(COUNTRY_UNIONS_FLAGS as unknown as GeoFlag[]),
].sort();

export const GENDER_FLAGS = [RAINBOW_FLAG_EMOJI, TRANS_FLAG_EMOJI] as const;

export const OTHERY_FLAGS = [
  CHEQUERED_FLAG_EMOJI,
  PIRATE_FLAG_EMOJI,
  BLACK_FLAG_EMOJI,
  WHITE_FLAG_EMOJI,
  TRIANGULAR_FLAG_EMOJI,
  CROSSED_FLAGS_EMOJI,
] as const;

// @internal
type GenderFlag = (typeof GENDER_FLAGS)[number];
// @internal
type OtherFlag = (typeof COUNTRY_UNIONS_FLAGS)[number];
// @internal
type Flag = GenderFlag | OtherFlag;

export const ALL_FLAGS: readonly Flag[] = [
  ...(GEO_FLAGS as unknown as Flag[]),
  ...(GENDER_FLAGS as unknown as Flag[]),
  ...(OTHERY_FLAGS as unknown as Flag[]),
].sort();
